name: Deploy complex
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t mkvskyx/complex-docker-react -f ./client/Dockerfile.dev .
      - name: Test
        run: docker run -e CI=true mkvskyx/complex-docker-react npm test -- --coverage